'use strict';(function(d){function c(){this._events={};this._maxListeners=10}function b(a,b,e,c,d){this.type=a;this.listener=b;this.scope=e;this.once=c;this.instance=d}b.prototype.fire=function(a){this.listener.apply(this.scope||this.instance,a);if(this.once)return this.instance.removeListener(this.type,this.listener,this.scope),!1};c.prototype.eachListener=function(a,b){var e=null,c=null,d=null;if(this._events.hasOwnProperty(a)){c=this._events[a];for(e=0;e<c.length;e+=1)if(d=b.call(this,c[e],e),
!1===d)e-=1;else if(!0===d)break}return this};c.prototype.addListener=function(a,g,e,c){this._events.hasOwnProperty(a)||(this._events[a]=[]);this._events[a].push(new b(a,g,e,c,this));this.emit("newListener",a,g,e,c);this._maxListeners&&!this._events[a].warned&&this._events[a].length>this._maxListeners&&("undefined"!==typeof console&&console.warn("Possible EventEmitter memory leak detected. "+this._events[a].length+" listeners added. Use emitter.setMaxListeners() to increase limit."),this._events[a].warned=
!0);return this};c.prototype.on=c.prototype.addListener;c.prototype.once=function(a,b,e){return this.addListener(a,b,e,!0)};c.prototype.removeListener=function(a,b,e){this.eachListener(a,function(c,d){c.listener===b&&(!e||c.scope===e)&&this._events[a].splice(d,1)});this._events[a]&&0===this._events[a].length&&delete this._events[a];return this};c.prototype.off=c.prototype.removeListener;c.prototype.removeAllListeners=function(a){a&&this._events.hasOwnProperty(a)?delete this._events[a]:a||(this._events=
{});return this};c.prototype.listeners=function(a){if(this._events.hasOwnProperty(a)){var b=[];this.eachListener(a,function(a){b.push(a.listener)});return b}return[]};c.prototype.emit=function(a){for(var b=[],e=null,e=1;e<arguments.length;e+=1)b.push(arguments[e]);this.eachListener(a,function(a){return a.fire(b)});return this};c.prototype.setMaxListeners=function(a){this._maxListeners=a;return this};"function"===typeof define&&define.amd?define(function(){return c}):d.EventEmitter=c})(this);
StackExchange.realtime=function(){function d(a){StackExchange.options.user.isDeveloper&&console.log(a)}function c(){r.on("hb",function(a){l.send(a)})}function b(a){u?(d("sending: "+a),l.send(a)):t.push(a)}function a(a,b){1!=$("#vote-accepted-"+a.answerid).length&&($(".vote-accepted-on").remove(),b||$('.vote input[value="'+a.answerid+'"]').parent().append('<span class="vote-accepted-on" title="The question owner accepted this as the best answer">accepted</span>'))}function g(){$("#new-answer-activity").remove();
$("#answers-header").prepend(p)}function e(a){var b=$(".question[data-questionid="+a.id+"], .answer[data-answerid="+a.id+"]"),e=$('<div class="new-post-activity" data-postid="'+a.id+'">an edit has been made to this post; click to load</div>');0<b.find(".new-post-activity[data-postid="+a.id+"]").length||b.prepend(e.click(function(){$(".new-post-activity[data-postid="+a.id+"]").remove();$.get("/posts/"+a.id+"/ajax-load-mini?title=true",q(b.find(".postcell, .answercell"),a))}))}function h(a,b){return a.index<
b.index?-1:a.index>b.index?1:0}function j(){var a=[],b;for(b in n)n.hasOwnProperty(b)&&a.push(n[b]);a=a.sort(h);for(b=0;b<a.length;b++){var e=a[b];$("#question-summary-"+e.id).remove();$(e.body).prependTo("#question-mini-list, #questions").hide().fadeIn()}i(0);null!=StackExchange.options.user.accountId&&StackExchange.tagPreferences.applyPrefs(!0,w);"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);k();$(".new-post-activity").remove();n={}}function i(a){var b=document.title.replace(/^\(\d*\*?\) /,
"");0<a&&(b="("+a+") "+b);window.setTimeout(function(){$(document).attr("title",b)},200)}function k(){for(var a=$("span.relativetime"),b=0;b<a.length;b++)if(a[b].title){var e;e=new Date(a[b].title);e=((new Date).getTime()-e.getTime())/1E3;var f=Math.floor(e/86400);if(e=isNaN(f)||0>f||31<=f?void 0:0==f&&(2>e&&"just now"||60>e&&Math.floor(e)+(s?"s ago":" secs ago")||120>e&&(s?"1m ago":"1 min ago")||3600>e&&Math.floor(e/60)+(s?"m ago":" mins ago")||7200>e&&(s?"1h ago":"1 hour ago")||86400>e&&Math.floor(e/
3600)+(s?"h ago":" hours ago")))a[b].innerHTML=e}}var f,l,n={},o=[],m=0,t=[],u=!1,s=!1,w,r=new EventEmitter,p=function(){var a=Object.keys(o).length;return $('<div id="new-answer-activity">'+a+" new answer"+(1<a?"s":"")+" to this question</div>").click(function(){StackExchange.realtime.expandAnswers()})},q=function(a,b){return function(e){var f=$(e).find(".postcell, .answercell");a.replaceWith(f.hide());e=$(e).attr("data-title");null!=e&&$("h1 a.question-hyperlink").text(e);f.fadeIn(400,function(){StackExchange.question.canViewVoteCounts()&&
StackExchange.vote.bindFetchVoteCounts();styleCode()});StackExchange.comments.init({post:f});StackExchange.vote.init(b.id);StackExchange.vote||StackExchange.question.bindAnonymousVoteDisclaimers();a.find("a[id^='link-post-']").click(function(a){if(!a.ctrlKey&&!a.metaKey)return StackExchange.question.showShareTip($(this),options.showCitation),!1});StackExchange.question.bindSuggestedEditPopupLinks();StackExchange.question.initShareLinks();window.history.pushState(b,"new post","#"+b.id)}},v=function(){var a=
Object.keys(n).length;i(a);return $('<div class="new-post-activity">'+a+" question"+(1<a?"s":"")+" with new activity</div>").click(function(){StackExchange.realtime.expandActiveQuestions()})};return{init:function(a){f=a;if("WebSocket"in window||"MozWebSocket"in window){if(l)try{d("closing WebSocket"),l.close()}catch(b){}l||(d("opening WebSocket"),l="WebSocket"in window?new WebSocket(f):new MozWebSocket(f),l.onopen=function(){if(!u){u=!0;for(var a=0,b=t.length;a<b;a++)d("sending: "+t[a]),l.send(t[a]);
t=[]}d("WebSocket opened");c();setInterval(k,6E4)},l.onmessage=function(a){a=$.parseJSON(a.data);r.emit(a.action,a.data)},l.onclose=function(){l=null;d("WebSocket closed");5>m&&(m++,d("reconnect attempt:"+m),setTimeout('StackExchange.realtime.init("'+f+'")',500))},l.onerror=function(){d("WebSocket failed");l=null})}},expandActiveQuestions:j,expandAnswers:function(){var a=$("#answers #answers-header .answers-subheader h2"),b=parseInt(a.text().match(/^\d*\*?/))+o.length;isNaN(b)&&(b=o.length);a.text(b+
" Answer"+(1<b?"s":""));$("#new-answer-activity").remove();var e=$("#answers #answers-header");$.each(o,function(a,b){$.get("/posts/"+b+"/ajax-load-mini",function(a){a=$(a);a.insertAfter(e).hide().fadeIn(400,function(){StackExchange.question.canViewVoteCounts()&&StackExchange.vote.bindFetchVoteCounts();styleCode()});StackExchange.comments.init({post:a});StackExchange.vote.init(b)})});StackExchange.vote||StackExchange.question.bindAnonymousVoteDisclaimers();e.find("a[id^='link-post-']").click(function(a){if(!a.ctrlKey&&
!a.metaKey)return StackExchange.question.showShareTip($(this),options.showCitation),!1});StackExchange.question.bindSuggestedEditPopupLinks();StackExchange.question.initShareLinks();k();o=[]},subscribeToActiveQuestions:function(a,e,f,c,g,d,h){a=a+"-"+e;w=f;s=d;b(a);r.on(a,function(a){a=$.parseJSON(a);if(null!=g)for(var b=0;b<g.length;b++)if(-1==$.inArray(g[b],a.tags))return;null!=StackExchange.options.user.accountId&&StackExchange.tagPreferences.isIgnored(a.body)||(n[a.id]={id:a.id,body:a.body,index:(new Date).getTime(),
siteid:a.siteid},$(".new-post-activity").remove(),$("#question-mini-list, #questions").prepend(v),c&&j());null!=h&&h(a)})},subscribeToInboxNotifications:function(){if(null!=StackExchange.options.user.accountId){var a=StackExchange.options.user.accountId+"-inbox";b(a);r.on(a,function(a){$(".unreadCount").remove();var b=$('<a class="unreadCount" title="unread messages in your inbox">'+a+"</a>").insertAfter(".genu");$("#portalLink .unreadCount").css({marginTop:b.css("margin-top"),opacity:1},2E3);genuwine.setUnreadCount(a)})}},
subscribeToQuestion:function(f,c){var d=f+"-question-"+c;b(d);r.on(d,function(b){b=$.parseJSON(b);if(b.acctid!=StackExchange.options.user.accountId)switch(b.a){case "score":var f=$('.vote input[value="'+b.id+'"]').siblings(".vote-count-post");f.text()!=b.score&&(f.text(b.score),0==$(":animated").length&&f.fadeTo("fast",0.7).fadeTo("fast",1),StackExchange.question.canViewVoteCounts()&&StackExchange.vote.bindFetchVoteCounts());break;case "comment-add":0==$("#comment-"+b.commentid).length&&(b=$("#comments-link-"+
b.id),f=b.data("comments-count")||0,f++,b.data("comments-count",f),b.attr("title","expand to show all comments on this post, or add one of your own"),b.html("add / show <b>"+f+"</b> more comment"+(1<f?"s":"")).show().fadeTo("fast",0.7).fadeTo("fast",1));break;case "answer-add":0==$("#answer-"+b.answerid).length&&(o.push(b.answerid),StackExchange.cardiologist.isHeartBeating()?StackExchange.helpers.DelayedReaction(g,5E3).trigger():g(),StackExchange.cardiologist.notifiedOfNewAnswer());break;case "accept":a(b);
break;case "unaccept":a(b,!0);break;case "post-edit":e(b)}})},subscribeToReputationNotifications:function(a){null!=StackExchange.options.user.accountId&&(a=a+"-"+StackExchange.options.user.userId+"-reputation",b(a),r.on(a,function(a){var b=$("#hlinks .reputation-score");b.text()!=a.score&&(0==$(":animated").length&&b.fadeTo("fast",0.8).fadeTo("fast",1),b.text(a))}))},subscribeToSuggestedEdits:function(a){a+="-suggested-edits-count";b(a);r.on(a,function(a){var b=$(".suggested-edits-count");b.text()!=
a&&(0==$(":animated").length&&b.fadeTo("fast",0.5).fadeTo("fast",1),b.text(a))})},updateRelativeDates:k}}();"use strict";StackExchange.anonymous={};
var gauth=function(){return{informStackAuth:function(d){if(gauth.enabled()){var c=document.domain;"meta."==c.substr(0,5)&&(c=c.substr(4,c.length-4));var b=$.cookie("gauth");if(null==b)$.cookie("gauth",null,{path:"/",domain:c}),$.cookie("gauth",null,{path:"/",domain:document.domain});else{"."!=c.charAt(0)&&(c="."+c);$.cookie("gauth",null,{path:"/",domain:c});$.cookie("gauth",null,{path:"/",domain:document.domain});var a=b.indexOf(":"),c=b.substr(0,a),b=b.substr(a+1),g=d+"/auth/global/write?authToken="+
encodeURIComponent(c)+"&nonce="+encodeURIComponent(b);$(document).ready(function(){$("#footer").append("<iframe style='display:none' src='"+g+"'></iframe>")})}}},checkStackAuth:function(d){if(gauth.enabled()&&null==$.cookie("gauthed")){$.cookie("gauthed","1",{path:"/"});var c=function(b){if(b.origin==d)if("No Local Storage"==b.data)gauth.noGAuthStorage();else if("No Session"==b.data)gauth.noGAuthSession();else{var a=b.data.substr(0,b.data.indexOf(",")),b=b.data.substr(b.data.indexOf(",")+1);$.post("/users/login/global",
{authToken:a,nonce:b},function(a){gauth.globallyAuthed(a)},"json")}};window.attachEvent?window.attachEvent("onmessage",c):window.addEventListener("message",c,!1);$.post("/users/login/global/request","",function(b){var a=d+"/auth/global/read?request="+encodeURIComponent(b.token)+"&nonce="+encodeURIComponent(b.nonce);$(document).ready(function(){$("#footer").append("<iframe id='global-auth-frame' style='display:none' src='"+a+"'></iframe>")})},"json")}},enabled:function(){$.cookie("enabledCheck","1");
if(null==$.cookie("enabledCheck"))return!1;$.cookie("enabledCheck",null);return"undefined"==typeof localStorage?!1:!0},noGAuthStorage:function(){},noGAuthSession:function(){},globallyAuthed:function(d){if(d&&d.Message){var d=d.Message+" ",c,b=!1,a=""+window.location,g=a.indexOf("returnurl=");if(-1!=g){var e=a.indexOf("&",g);-1==e&&(e=a.length);c=decodeURIComponent(a.substring(g+10,e));c=/^(?:http:\/\/|\/)/.test(c)?c.replace(/[^-a-z0-9+&@#\/%?=~_|!:,.;()]/g,""):null}-1!=a.indexOf("/users/login")&&
(b=!0,c=c||"/");StackExchange.helpers.showFancyOverlay({message:b?d+"<br>You are being redirected...":d+(c?"<a href=\"javascript:window.location='"+c+"'\">Click here</a> to return to your last location.":'<a href="javascript:location.reload(true)">Click here</a> to refresh the page.'),showClose:!b,complete:function(){b&&(window.location=c)}})}}}}(),genuwine=function(){var d,c="",b,a,g=[],e=function(){return $(".genu").hasClass("genu-on")},h=function(){var e=$(".genu"),f=$("#seWrapper");if(0==f.length||
0<b||a){i();var f=$("#seWrapper"),c;0<b?(c=$("#seTabInbox"),u(c)):a?(c=$("#seTabNotices"),k(c)):(c=$("#seTabHot"),n(c));c.addClass("seCurrent")}if(c=e.hasClass("genu-on")){$(".unreadCountTab").remove();$(".itemBoxNew").removeClass("itemBoxNew");f.fadeOut("fast");for(f=0;f<g.length;f++)g[f]();g=[];0<a&&$("#portalLink .unreadCount").text(""+a).addClass("newNotices").show().click(h)}else f.fadeIn("fast"),$(".unreadCount").hide();e.toggleClass("genu-on",!c);-1==b&&$(e).ready(function(){$("#seTabInbox").hide()});
j($("#seTabInbox"),$("#seTabNotices"))},j=function(e,f){StackExchange.options.site.isNoticesTabEnabled&&a&&0==f.find(".unreadCountTab").length&&f.prepend('<span class="unreadCountTab newNotices">'+a+"</span>");0<b&&0==e.find(".unreadCountTab").length&&e.prepend('<span class="unreadCountTab">'+b+"</span>")},i=function(){$("#seWrapper").remove();var a='<div id="seWrapper" style="position:absolute; display:none;"><div class="seIntro"><a href="'+c+'">Stack Exchange</a> is a network of free, community-driven Q&A sites.</div><div class="seNav"><ul class="seNavLinks"><li><a id="seTabHot">Hot Questions</a></li><li><a id="seTabSites">All Sites</a></li><li><a id="seTabInbox">Inbox</a></li>'+
(!StackExchange.options.user.isAnonymous&&StackExchange.options.site.isNoticesTabEnabled?'<li><a id="seTabNotices">Notifications</a></li>':"")+'</ul></div><div class="seContainer"></div><div class="seFooter">'+(!StackExchange.options.user.isAnonymous?'<div id="seTabEmail" class="seEmailAccount"><a>email settings</a></div>':"")+'<a id="seClose">close</a></div></div>',b=$("#hlinks"),b=b.height()+b.offset().top+5;$(a).appendTo("#portalLink").css({top:b}).find("ul.seNavLinks a, #seTabEmail").click(function(){var a=
$(this);$(".seNavLinks a").removeClass("seCurrent");a.addClass("seCurrent");switch(a.attr("id")){case "seTabHot":n(a);$("#seContainerSites, #seContainerInbox, #seContainerEmail, #seContainerNotices").hide();$("#seContainerHot").fadeIn("fast");break;case "seTabSites":0==$("#seContainerSites").length&&l(a);$("#seContainerHot, #seContainerInbox, #seContainerEmail, #seContainerNotices").hide();$("#seContainerSites").fadeIn("fast");break;case "seTabInbox":u(a);$("#seContainerHot, #seContainerSites, #seContainerEmail, #seContainerNotices").hide();
$("#seContainerInbox").fadeIn("fast");break;case "seTabEmail":0==$("#seContainerEmail").length&&o(a);$("#seContainerHot, #seContainerSites, #seContainerInbox, #seContainerNotices").hide();$("#seContainerEmail").fadeIn("fast");break;case "seTabNotices":k(a),$("#seContainerHot, #seContainerSites, #seContainerInbox, #seContainerEmail").hide(),$("#seContainerNotices").fadeIn("fast")}});$("#seClose").click(function(){h()})},k=function(a){0==$("#seContainerNotices").length&&p(a,"/notices/genuwine?userId="+
StackExchange.options.user.id,"jsonp",f,!0)},f=function(b,e){for(var f='<div id="seContainerNotices" style="display:none">',c=0;c<e.length;c++)var d=e[c],f=f+('<div class="noticeBox'+(d.is_unread?" itemBoxNew":"")+'"><a href="'+d.site_url+'" class="siteLinkFavicon"><img src="'+d.icon+'"></a><div class="siteInfo"><p>'+d.text+"</p></div></div>");q(b,f+"</div>");g.push(function(){a=0;j($("#seTabInbox"),$("#seTabNotices"))});a=0},l=function(a){p(a,c+"/genuwine/sites?callback=?&host="+document.location.host+
(d?"&accountId="+d:""),"jsonp",t)},n=function(a){0==$("#seContainerHot").length&&p(a,c+"/genuwine?callback=?","jsonp",m)},o=function(a){p(a,"/accounts/email-settings","json",function(a,b){function e(){$("#email-save").removeAttr("disabled");$("#email-confirmation").html("")}q(a,'<div id="seContainerEmail" style="display:none; font-size:11px;"><div class="itemBox" style="border-bottom: 0px"><p>Would you like to receive unread inbox messages via email?</p><div>Email: <input id="email-notify" name="email-notify" style="width:300px;" value="'+
b.verifiedEmail+'"></input></div><div><input type="radio" name="optIn" value="true" id="email-enable"'+(!0==b.optIn?'checked="checked"':"")+'"> <label for="email-enable">Email me my unread inbox messages </label> <select id="email-freq"><option value="3">every 3 hours</option><option value="24">daily</option><option value="168">weekly</option></select> </div><div><input type="radio" name="optIn" value="false" id="email-disable"'+(!0!=b.optIn?'checked="checked"':"")+'"> <label for="email-disable">Do not email me inbox messages</label></input></div><div><input type="button" name="save" id="email-save" value="Save" disabled="disabled"></input></div><div id="email-confirmation" style="display:none;"></div></div></div>');
$("#email-freq").val(b.freq).on("click focus",function(){$("#email-enable").prop("checked",!0)});$("#email-notify").focus().keyup(e);$("#email-enable, #email-disable, #email-freq").change(e);$("#email-save").click(function(){v();$.post("/accounts/verified-email-set",{email:$("#email-notify").val(),fkey:StackExchange.options.user.fkey,optin:$("input[name=optIn]:checked").val(),freq:$("#email-freq").val()},function(a){$(".seContainer").removeSpinner();$("#email-confirmation").html(a.message).fadeIn();
a.success&&$("#email-save").attr("disabled","disabled")},"json")})},!0)},m=function(a,b){for(var e=$("<div/>"),f='<div id="seContainerHot" style="display:none">',c=0;c<b.length;c++)var g=b[c],d=g.SiteId,h='href="http://'+d+"/q/"+g.Id+'?hq=1"',i=parseInt(g.DisplayScore,10),f=f+('<div class="itemBox"><a '+h+' class="seNumAnswer">'+i+'</a><div class="siteInfo"><p><a '+h+">"+e.text(g.Title).html()+'</a></p><a href="http://'+d+'" class="siteLink">'+d+"</a></div></div>");q(a,f+"</div>")},l=function(a){p(a,
c+"/genuwine/sites?callback=?&host="+document.location.host+(d?"&accountId="+d:""),"jsonp",t)},t=function(a,b){for(var e='<div id="seContainerSites" style="display:none">',f=0;f<b.length;f++)var c=b[f],g=c.Name,d='href="http://'+c.Id+'?as=1"',e=e+('<div class="itemBox"><a '+d+' class="siteFavicon"><img src="'+c.FaviconUrl+'" alt="'+g+'"></a><div class="siteInfo"><p><a '+d+">"+g+"</a></p><a "+d+' class="siteLink">'+c.Description+"</a></div></div>");q(a,e+"</div>")},u=function(a){-1!=b&&(0==$("#seContainerInbox").length||
0<b)&&s(a)},s=function(a){p(a,"/inbox/genuwine","json",w,!0)},w=function(a,e){for(var f='<div id="seContainerInbox" style="display:none">',c=0;c<e.length;c++){var h=e[c],i='href="'+h.Url+'"',k='title="'+h.CreationDate+'"',l=h.Count,f=f+('<div class="itemBox'+(h.IsNew?" itemBoxNew":"")+'"><a '+i+' class="siteLinkFavicon"><img src="'+h.FaviconUrl+'" alt="'+h.SiteUrl+'"></a><div class="siteInfo">');"careers message"==h.Type?f+="<p><a "+i+' style="font-weight:normal"><b>'+h.Title+"</b> wants to contact you on <b>Stack Overflow Careers</b></a></p>":
"invitation"==h.Type?(k=h.Count,f+="<p><a "+i+' style="font-weight:normal"><b>'+k+"</b> "+("invitation"+(1<k?"s":""))+" awarded on <b>Stack Overflow Careers</b></a></p>"):f+="<p>"+(1<l?l+" ":"")+h.Type+" on <a "+i+" "+k+">"+h.Title+"</a></p>";f+='<p class="inboxSummary">'+(h.Summary||"")+"</p></div></div>"}d&&5<=e.length&&(f+='<div class="itemMoreContainer"><div class="seIntro"><a href="http://stackexchange.com/users/'+d+'?tab=inbox">more inbox messages &hellip;</a></div></div>');q(a,f+"</div>");
g.push(function(){b=0;j($("#seTabInbox"),$("#seTabNotices"))});b=0},r={},p=function(a,b,f,e,c){var g=a.attr("id");if(r[g])v();else{r[g]=!0;v();var d=function(){r[g]=!1;StackExchange.helpers.showErrorPopup($(".seContainer"),"An error occurred while loading - please try again.")};$.ajax({type:"GET",url:b,dataType:f,success:function(b){r[g]=!1;b&&(0<b.length||c)?e(a,b):d()},error:d,complete:function(){$(".seContainer").removeSpinner()}})}},q=function(a,b){var f=$(b);f.prependTo(".seContainer");a.hasClass("seCurrent")&&
f.fadeIn("fast")},v=function(){StackExchange.helpers.removeSpinner();StackExchange.helpers.addSpinner(".seContainer",{position:"relative",left:"10px",top:"10px"})},y=function(){var a=$("#portalLink .unreadCount"),b=a.css("margin-top");a.css({marginTop:-20,opacity:0}).show().animate({marginTop:b,opacity:1},2E3)},x=function(){var a=$(".unreadCount"),b=a.data("events");(!b||!b.click)&&0<a.length&&a.click(h)};return{isVisible:e,click:h,setUnreadCount:function(a){b=a;var f=$("#seTabInbox");0<a?($("#portalLink .unreadCount").text(b),
f.hasClass("seCurrent")&&e()&&s(f),y()):$("#portalLink .unreadCount").text("").hide();$("#portalLink .unreadCount").removeClass("newNotices");x()},animateInbox:y,init:function(f,g,i){var k=$(".genu");1<=k.length&&(k[0].onclick=null);d=f;c=k.attr("href");b=g;a=i;!(0<b)&&StackExchange.options.site.isNoticesTabEnabled&&(99<a&&(a=99),0<a&&$("#portalLink .unreadCount").text(""+a).addClass("newNotices"),x());k.removeAttr("href").click(h);x();$(document).click(function(a){e()&&!$.contains($("#portalLink")[0],
a.target)&&h()})}}}();
StackExchange.notify=function(){function d(a,b){var f=$("#dismissed-messages");f.val(f.val()+"~"+a+(b?" "+b:"")+"~")}function c(a,b){var f=$("#dismissed-messages").val();return!f?!1:RegExp("~"+a+(b?" "+b:"")+"~").test(f)}function b(a,b,f){var e=parseInt($("body").css("margin-top").match(/\d+/)),a=b*e/a;f?$("body:not(.no-message-slide)").animate({marginTop:a+"px"},"fast","linear"):$("body:not(.no-message-slide)").css("marginTop",a+"px")}var a=0,g=function(e,c){var f=$("#notify-"+e+(c?"-"+c:""));-1==
e?$.cookie("m","0",{expires:90,path:"/"}):-1<e&&$.post("/messages/mark-as-read",{messagetypeid:e,id:c?c:null});d(e,c);a--;f.fadeOut("fast",function(){b(a+1,a,!0);f.remove()})},e=function(b){a++;if(c(b.messageTypeId,b.id))return!1;var e="";b.messageTypeId&&(e=' id="notify-'+b.messageTypeId+(b.id?"-"+b.id:"")+'"');e="<div"+e+' style="display:none"><span class="notify-close"><a title="dismiss this notification">&times;</a></span><span class="notify-text">'+b.text+"</span>";if(b.showProfile)var f=encodeURIComponent("/users/"+
b.userId+"?tab=badges&sort=recent"),e=e+(' See your <a href="/messages/mark-as-read?messagetypeid='+b.messageTypeId+"&returnurl="+f+'">profile</a>.');e=$(e+"</div>");e.find(".notify-close").click(function(){b.close&&b.close();g(b.messageTypeId,b.id)});$("#notify-container").append(e);return!0},h=function(){$("#notify-container div").fadeIn("slow")},j=function(a,b){var f=$('<div class="link-more"><a>view '+a+" more notification"+(1!=a?"s":"")+"</a></div>");$("#notify-container").append(f);f.click(function(){f.detach();
for(var a=0;a<b.length;a++)e(b[a]);h()})};return{showMessages:function(c,g){for(var f=0,d=g?2:c.length,n=0;n<d&&n<c.length;n++)e(c[n])&&f++;b(a,f,!1);h();g&&f<c.length&&(d=c.slice(d),j(c.length-f,d))},show:function(a,b){$("body:not(.no-message-slide)").animate({marginTop:"2.5em"},"fast","linear");e({text:a,messageTypeId:b});h()},close:g,getMessageText:function(a){return $("#notify-"+a+" .notify-text").text()}}}();
function moveScroller(){var d=$("#scroller").width(),c=function(){var b=$(window).scrollTop(),a=$("#scroller-anchor").offset().top,c=$("#scroller");b>a?c.height()>$(window).height()?c.css({position:"fixed",top:"",bottom:"0px",width:d}):c.css({position:"fixed",top:"0px",bottom:"",width:d}):b<=a&&c.css({position:"relative",top:"",bottom:""})};$(window).scroll(c).resize(c);c()}
var styleCode=function(){return function(){"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);var d=!1;$("pre code").parent().each(function(){$(this).hasClass("prettyprint-override")&&($(this).removeClass("prettyprint-override").addClass("prettyprint"),d=!0);var c;if(c=!$(this).hasClass("prettyprint")){c=$(this);var b=$("#prettify-lang").text();""!=b?(c.addClass(b),c=!0):c=!1}c&&($(this).addClass("prettyprint"),d=!0)});d&&("undefined"!=typeof jtab?jtab.renderimplicit():StackExchange.using("prettify",
function(){StackExchange.prettify.applyCodeStyling()}))}}();
StackExchange.helpers.MagicPopup=function(d){function c(a,e){var f=$("<div id='"+d.id+"'/>").html(e),c=$("<div />").css({overflow:"hidden",position:"absolute",width:1,height:1,top:0,left:0}).append(f).appendTo("body"),h=d.showing(a,f),j={left:h.left};h.hasOwnProperty("bottom")?(j.bottom=h.bottom,j.top="auto"):j.top=h.top;var m;d.shown&&(m=function(){d.shown(a,f)});c.css(j).animate({height:f.outerHeight()+8,width:f.outerWidth()+8},300,m);b=function(){c.stop().remove();d.removed&&d.removed(a,f);b=g=
null};g=StackExchange.helpers.DelayedReaction(b,5);j=c;h.additional&&(j=j.add(h.additional));j.hover(g.cancel,g.trigger)}var b,a,g,e,h={},j=StackExchange.helpers.DelayedReaction(function(a,g){if(!e&&a){var f;d.cache&&"c_"+a in h?f=$.Deferred().resolve(h["c_"+a]):(f=$.ajax({type:"GET",url:a,dataType:"html"}),d.cache&&f.done(function(b){h["c_"+a]=b}));f.done(function(a){b&&b();""!=a&&c(g,a)})}},500);$(document).delegate(d.selector,{mouseenter:function(){if(g&&this===a)g.cancel();else return a=this,
j.trigger(d.getUrl(this),this),e=!1},mouseleave:function(){e=!0;j.cancel();g&&g.trigger()}})};
StackExchange.tagmenu=function(){function d(a){var a=$(a),b=a.attr("href");if(!b||"/"!=b.charAt(0))return null;b=a.text();if(-1<b.indexOf("*"))return null;a.attr("title","");return"/tags/"+encodeURIComponent(b)+"/subscriber-info"}function c(a,b){var c=$(a),d=c.offset(),i=c.outerHeight(),c={left:d.left},k=d.top+i,i=d.left+b.outerWidth();b.height()+k>$(window).height()+$(window).scrollTop()?c.bottom=$(window).height()-d.top-8:c.top=k;d=Math.max(1024,$(window).width());i>d&&(c.left-=i-d);return c}var b,
a;return{init:function(g){b=g;a||(a=!0,StackExchange.options.isMobile||(StackExchange.helpers.MagicPopup({selector:".post-tag:not(.user-tag)",id:"tag-menu",getUrl:d,showing:c,shown:function(a,c){b&&b(c,$(a).text())}}),$("#interesting-tags .post-tag").addClass("user-tag")))}}}();
StackExchange.usermenu=function(){function d(b,e){var c=$(b).find("img:first"),d=c.offset(),i=c.height(),k=c.width(),f=Math.max(k,i),l=64*i/f,f=64*k/f,n=e.find("img:first").css({width:f,height:l}),o=n.offset();n.css("visibility","hidden");a=c.clone().css({position:"absolute",zIndex:300,left:d.left,top:d.top,width:k,height:i}).appendTo("body");var m=function(){n[0].complete?(n.css("visibility","visible"),a.fadeOutAndRemove()):setTimeout(m,500)};a.animate({width:f,height:l,top:d.top+o.top},200,m);return{top:d.top,
left:d.left-o.left,additional:a}}function c(){a.remove()}var b,a;return{init:function(){b||(b=!0,StackExchange.options.isMobile||StackExchange.helpers.MagicPopup({selector:".user-hover .user-gravatar48, .user-hover .user-gravatar32",getUrl:function(a){a=/\/users\/([^/]+).*$/.exec($(a).closest(".user-hover").find(".user-details a").attr("href"));return!a?null:"/users/user-info/"+a[1]},cache:!0,id:"user-menu",showing:d,removed:c}))}}}();
StackExchange.chatAd=function(){function d(){var a=$(".question .post-taglist .post-tag");return!a.length?null:a.map(function(a,b){return $(b).text()}).get().join(" ")}function c(a){return 10>a?"0"+a:a}function b(a){var b=new Date;b.setTime(1E3*a);return[b.getUTCFullYear(),"-",c(b.getUTCMonth()+1),"-",c(b.getUTCDate())," ",c(b.getUTCHours()),":",c(b.getUTCMinutes()),":",c(b.getUTCSeconds()),"Z"].join("")}function a(a){var b=Math.floor((new Date).getTime()/1E3)-a,f=b%60,e=Math.floor(b/60),d=Math.floor(b/
3600);if(1>b)return"just now";if(60>b)return 1==f?"1 sec ago":f+" secs ago";if(3600>b)return 1==e?"1 min ago":e+" mins ago";if(86400>b)return 1==d?"1 hour ago":d+" hours ago";b=Math.floor(b/86400);if(1==b)return"yesterday";if(2>=b)return b+" days ago";a=new Date(1E3*a);return m[a.getMonth()]+" "+a.getDate()+" at "+a.getHours()+":"+c(a.getMinutes())}function g(a){var b=$("<div />");b.text(a);return b.html().replace('"',"&quot;")}function e(){$.get(f,null,function(a,b,f){i(a,b,f)})}function h(b){for(var f=
$('<div class="ad502-users" />'),e=0;e<b.length&&7>e;e++){var c=b[e],d=c.name;c.lastPost&&(d+=": "+a(c.lastPost));var g="http://www.gravatar.com/avatar/"+c.emailhash+"?s=23&d=identicon&r=PG",c=$('<a href="'+(k+"/users/"+c.id)+'" />');$("<img />").attr("title",d).attr("src",g).appendTo(c);f.append(c)}return f}function j(a){var b=a.user;return(a=a.userid)?'<a href="'+k+"/users/"+a+'">'+g(b)+"</a>":g(b)}function i(c){var f=$("#ad502-rooms");if(!c.error){f.html("");for(var d=c.rooms,i=0;i<d.length&&2>
i;i++){var m=d[i],p=k+"/rooms/"+m.id,q=$('<div class="ad502-room"></div>');q.append($('<h3 class="ad502-room-h3"><span class="ad502-room-title" title="'+g(m.name)+'"><a href="'+p+'">'+g(m.name)+"</a></span></h3>"));m.messages&&0<m.messages.length&&q.append($('<span title="'+b(m.lastPost)+'" class="ad502-last-message">'+a(m.lastPost)+" - "+j(m.messages[0])+"</span><br>"));m.singleImage?q.append($('<div class="ad502-users"><img src="'+k+"/rooms/users/"+m.id+'.jpeg" /></div>')):q.append(h(m.users));
f.append(q)}1<c.activeUsers?$("#h-chat-link").text(c.activeUsers+" People Chatting"):$("#h-chat-link").text("Visit Chat");$("#h-chat-link").attr("title",c.activeUsers+" users active in "+c.activeRooms+" rooms the last 60 minutes")}l<=o&&window.setTimeout(e,1E3*l);l+=n}var k,f,l=180,n=30,o=480,m="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");/^\/questions\/\d+/i.test(window.location.pathname)&&(o=0);return{init:function(a){k=a.chatUrl;f=a.reloadUrl;if(a.tagBased){var b=d();if(!b)return;
f+=(/\?/.test(f)?"&":"?")+"tags="+encodeURIComponent(b)}null===a.preloadData?e():i(a.preloadData,null,null)}}}();
StackExchange.helpers.noDiacritics=function(){var d={"\u00e0\u00e5\u00e1\u00e2\u00e4\u00e3\u00e5\u0105":"a","\u00e8\u00e9\u00ea\u00eb\u0119":"e","\u00ec\u00ed\u00ee\u00ef\u0131":"i","\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u0151":"o","\u00f9\u00fa\u00fb\u00fc":"u","\u00e7\u0107\u010d":"c","\u017c\u017a\u017e":"z","\u015b\u015f\u0161":"s","\u00f1\u0144":"n","\u00fd\u0178":"y","\u0142":"l","\u0111":"d","\u00df":"ss","\u011f":"g","\u00de":"th"};return function(c){for(var b in d)d.hasOwnProperty(b)&&(c=
c.replace(RegExp("["+b+"]"),d[b]));return c}}();function sanitizeAndSplitTags(d,c){for(var d=$.trim(d).replace(/([A-Za-z0-9])\+(?=[A-Za-z0-9])/g,"$1 "),b=d.split(/[\s|,;]+/),a=[],g=0;g<b.length;g++){var e=StackExchange.helpers.noDiacritics(b[g].toLowerCase()).replace(/_/g,"-"),e=e.replace(RegExp("[^a-z0-9.#+"+(c?"*":"")+"-]","g"),""),e=e.replace(/^[#+-]+/,""),e=e.replace(/[.-]+$/,"");0<e.length&&-1==$.inArray(e,a)&&a.push(e)}return a}
StackExchange.question=function(){var d=function(a,b){var c=null!=a;a||(a=$('div.question div.post-menu a:contains("link")'));var e=a.closest(".post-menu, .help-menu");if(a.hasClass("share-link"))e.find(".close-share-tip").click();else{a.addClass("share-link");var d=a.attr("id").substring(10),g=a.closest(".col-section").length?"section":a.closest("div.question").length?"question":"answer",h=$('<div class="share-tip" style="display:none">share a link to this '+g+'<input type="text" value="http://'+
document.location.host+a.attr("href")+'" style="display:block; width:292px;"><a class="close-share-tip" style="float:right">close</a></div>');b&&h.find(".close-share-tip").before('<a id="link-post-'+d+'" style="float:left">cite</a>');h.appendTo(e).fadeIn(c?"fast":0).bind("removing",function(){a.removeClass("share-link")}).find(".close-share-tip").click(function(){h.fadeOutAndRemove()}).end().find("input[type=text]").select()}},c=function(a){var b=$("#post-form h2:first"),c=b.wrap("<div />").parent(),
e=c.wrap("<div />").parent(),d=$("<div />").prependTo(e),g=e.height(),h=$("<div />"),a=$(a),j=parseInt(b.css("margin-bottom")),i=$("#content"),k=$("#wmd-input").outerWidth(),p=i.offset().left>b.offset().left-5&&"visible"!=i.css("overflow-x");h.css({height:0,overflowY:"hidden"}).appendTo(c).append(a);e.css({height:g,position:"relative"});c.css({position:"absolute",bottom:-j,width:k});d.addClass("answer-help-background").css({position:"absolute",bottom:-j,height:0,width:k});p&&(d.css("left",0),c.animate({paddingLeft:5},
1E3));h.animate({height:a.height()+j+10},1E3);d.animate({height:a.height()+j+10+g},1E3);$("<div style='float:right;margin-top:10px;'><a href='#'>ok</a></div>").hide().prependTo(c).fadeIn(1E3).find("a").one("click",function(a){var e=$(this).parent();setTimeout(function(){e.remove()},1);h.animate({height:0},1E3,function(){h.add(d).remove();b.unwrap().unwrap()});d.animate({height:0},1E3);p&&c.animate({paddingLeft:0},1E3);a.preventDefault()})},b=function(){$.get("/posts/answer-help").then(c)},a,g,e,h=
function(){var a=window.location.href;0>a.indexOf("#")||(a=a.match(/#(\d+|comment(\d+)_(\d+))/i))&&(a[2]?j(a[2],a[3]):i($(".answer[data-answerid="+a[1]+"]")))},j=function(a,b){var c="#comment-"+a,e=$(c);e.length?i(e):StackExchange.comments.loadAll($("#comments-link-"+b)).done(function(){i($(c))})},i=function(b){var c=e;b.css({backgroundColor:a}).animate({backgroundColor:c},2E3,"linear",function(){$(this).css("background-color","")});b.is(".comment")&&b[0].scrollIntoView(!0)},k=function(a){a=a||{};
$('.post-menu a:contains("link")').live("click",function(b){if(!b.ctrlKey&&!b.metaKey)return d($(this),a.showCitation),!1})};return{initTitleSearch:function(a,b,c){var e=0,d,g=function(){var g=a.val();if(g!=d){for(var h=g.split(" "),j=0,i=0;i<h.length;i++)0<$.trim(h[i]).length&&j++;h=(new Date).getTime();i=(h-e)/1E3;3>j||5>i&&!a.hasClass("edit-field-overlayed")||(e=h,d=g,c&&(document.title=g+" - "+c),StackExchange.helpers.addSpinner(b),b.load("/search/titles?like="+escape(g),null,function(a){/\<label\>/i.exec(a)||
(e=0);setTimeout(function(){b.find(".answer-link a").attr("target","_blank")},1)}))}},h=function(){e=0;g()};a.keyup(g).blur(h);setInterval(g,5E3);return h},showShareTip:d,getQuestionId:function(a){a=(a?a.closest(".question"):$(".question")).data("questionid");if(!a)throw Error("getQuestionId could not find an id");return a},highlightComment:j,initShareLinks:k,canViewVoteCounts:function(){return g},init:function(c){StackExchange.question.fullInit?StackExchange.question.fullInit(c):StackExchange.question.bindAnonymousVoteDisclaimers();
StackExchange.comments.init({autoShowCommentHelp:c.autoShowCommentHelp});c.showShareTip&&d();$("input.anon-vote").live("click",function(){var a=$(this),b=a.postId(),c=a.parent();c.closest(".question,.answer").unbind("mouseenter.helpful").unbind("mouseleave.helpful");c.text("sending feedback ...");setTimeout(function(){c.text("Thank you for your feedback.")},500);$.ajax({type:"POST",url:"/vote/anon/"+b,data:{votetypeid:"Yes"==a.val()?2:3},complete:function(){}})});var j=$(".was-this-helpful"),i=j.css("color"),
o=$(".post-text").css("color");j.each(function(){var a=$(this),b=a.text();a.closest(".answer, .question").bind("mouseenter.helpful",function(){a.html("Was this post useful to you? &nbsp;&nbsp;<input style='display:none;' class='anon-vote' type='button' value='Yes'/> &nbsp;<input style='display:none;' class='anon-vote' type='button' value='No'/>").animate({color:o},"fast","linear").find("input").fadeIn("fast")}).bind("mouseleave.helpful",function(){a.text(b).animate({color:i},"fast","linear")})});
k(c);if(c.showAnswerHelp)$("#wmd-input").one("focus",b);c.showCitation&&$("div.share-tip a[id^='link-post-']").live("click",function(){$(this).closest(".post-menu").find(".close-share-tip").click();citation.show($(this))});e=c.backgroundColor;a=c.highlightColor;g=c.canViewVoteCounts;h(c)}}}();
StackExchange.question.bindAnonymousVoteDisclaimers=function(){function d(c){return function(b){var a='Please <a href="/users/login?returnurl='+escape(document.location)+'">login or register</a> to '+c+" this post.";StackExchange.helpers.showErrorPopup($(this).parent(),a);var a="",d=$(this).prop("className"),e=$(this).closest(".answer").length?"answer":"question";/vote-up/.test(d)?a="?vote=up&type="+e:/vote-down/.test(d)?a="?vote=down&type="+e:/star/.test(d)&&(a="?vote=favorite");StackExchange.helpers.fireAndForget("/analytics/user/try-vote"+
a);b.preventDefault()}}$(".vote-up-off, .vote-down-off").click(d("vote for"));$("div.post-menu a[id^='flag-post-']").unbind("click").click(d("flag"));$(".star-off:not(.disabled)").live("click",d("favorite"))};
StackExchange.comments=function(){function d(a,b){this.postId=a;this.jDiv=b;this.jCommentsLink=$("#comments-link-"+a)}function c(b){var c=(b.constructor===$?b:$(b)).closest(".question, .answer, div[id^='post-']").find(".comments"),b=c.attr("id").replace(/^comments-/,"");if(a[b])return a[b];c=new d(b,c);return a[b]=c}function b(){if(0!=$(".question[data-questionid]").length){var a=StackExchange.question.getQuestionId();$(".comment .comment-date > span").each(function(){var b=$(this),c=b.closest(".answer"),
c=c&&c.length?c.data("answerid"):0,d=b.closest(".comment").attr("id").substr(8);b.wrap('<a class="comment-link" onclick="StackExchange.question.highlightComment({cid}, {aid})" href="{hash}"></a>'.format({hash:"#comment"+d+"_"+(c?c:a),cid:d,aid:c}))})}}var a={},g=function(){};d.prototype={checkDiscussion:g,ensureInput:g,commentsShown:function(){this.jCommentsLink.hide();this.jCommentsLink.data("comments-count",0)},addShow:function(a){var b=this;this.loadAllComments().done(function(){b.jCommentsLink.hide();
b.checkDiscussion()});var c=this.ensureInput();c&&!a&&c.focus()},ajax:function(a,b,c,d){c&&!d&&StackExchange.helpers.addSpinner(c,{"margin-left":"10px"});var g=this;return $.ajax(a).fail(function(a){$(".error-notification").fadeOut("fast",function(){$(this).remove()});a=a.responseText;if(!a||100<=a.length)a="An error occured"+(b?" "+b:"");StackExchange.helpers.showErrorPopup(c||g.jDiv,a);c&&!d&&StackExchange.helpers.removeSpinner()}).done(StackExchange.helpers.removeSpinner).promise()},showComments:function(a){this.jDiv.find(" > table > tbody").html(a);
this.jCommentsLink.text("add comment");"undefined"!=typeof MathJax&&MathJax.Hub.Queue(["Typeset",MathJax.Hub]);b();this.commentsShown()},loadAllComments:function(a){this.jDiv.removeClass("dno");if(!a&&!/more comment/.test($("#comments-link-"+this.postId).text()))return $.Deferred().resolve().promise();var b=this;return this.ajax({type:"GET",url:"/posts/"+this.postId+"/comments",dataType:"html"},"while fetching comments").done(function(a){b.showComments(a)}).promise()}};return{init:function(a){a=a&&
a.post||document;$("a[id^='comments-link-']",a).click(function(){var a=/more comment/.test($(this).text());c(this).addShow(a)});a==document&&b()},loadAll:function(a){return c(a).loadAllComments(!0)},extendPostUi:function(a){for(var b in a)a.hasOwnProperty(b)&&(d.prototype[b]=a[b])},uiForPost:c}}();
StackExchange.share=function(){function d(b,a,c){window.open(b,a,c)||(window.location.href=b)}function c(b,a){var c=b.indexOf("?"),e=b.indexOf("#");return-1==c?-1==e?b+"?"+a:b.substring(0,e)+"?"+a+b.substring(e):-1==e?b+"&"+a:b.substring(0,e)+"&"+a+b.substring(e)}return{gplus:function(b,a){a=c(a,"sgp=1");b.click(function(){d("https://plus.google.com/share?url="+a,"sharegplus","toolbar=1,status=1,resizable=1,scrollbars=1,width=600,height=500")})},twitter:function(b,a,g){a=c(a,"stw=1");b.click(function(){d("http://twitter.com/share?url="+
a+"&ref=twitbtn&text="+g,"sharetwitter","toolbar=1,status=1,resizable=1,scrollbars=1,width=800,height=526")})},facebook:function(b,a,g){a=c(a,"sfb=1");b.click(function(){d("http://www.facebook.com/sharer.php?u="+a+"&ref=fbshare&t="+g,"sharefacebook","toolbar=1,status=1,resizable=1,scrollbars=1,width=626,height=436")})}}}();
function initTagRenderer(d,c){window.tagRenderer||(window.tagRendererRaw=function(b,a){var a=a||"",g="";a||(d&&-1<$.inArray(b,d)?g=" required-tag":c&&-1<$.inArray(b,c)&&(g=" moderator-tag"));return"<a class='post-tag"+g+"' href='"+a+"/questions/tagged/"+encodeURIComponent(b)+"' title=\"show questions tagged '"+b+"'\" rel='tag'>"+b+"</a>"},window.tagRenderer=function(b,a){return $(tagRendererRaw(b,a))})}
function showFadingHelpText(d){d.wrap('<div class="dno" />').show().parent().fadeIn("slow",function(){$(this).children().unwrap()})}
function initFadingHelpText(){var d={"wmd-input":"#how-to-format",tagnames:"#how-to-tag","tag-editor":"#how-to-tag",title:"#how-to-title","wmd-input-42":"#how-to-format"},c=$("#wmd-input, #tagnames, #title, .tag-editor input, #wmd-input-42"),b=function(a){return $(a).parent().hasClass("tag-editor")?d["tag-editor"]:d[$(a).attr("id")]};c.focus(function(){var a=b(this);c.each(function(){var c=b(this);c!=a&&$(c).hide()});var d=$(a);d.is(":visible")||showFadingHelpText(d)})}
$.fn.extend({postId:function(){var d=this.first();if(!d.hasClass("answer")||!d.hasClass("question"))d=d.closest(".answer, .question");return parseInt(d.find(".vote input")[0].value)}});
StackExchange.newsletterAd=function(){function d(b){b=$('<div id="lightbox-panel" class="popup" style="display:block"></div>').append('<div class="popup-close"><a title="close this popup (or hit Esc)">&times;</a></div>').append(b);$('<div id="lightbox"></div>').appendTo($("body")).css("height",$(document).height()).fadeIn("fast");b.appendTo($("body")).center().fadeIn("fast").find(".popup-close").click(function(){$("#lightbox, #lightbox-panel").fadeOutAndRemove()})}function c(){var b=StackExchange.options.site.name,
a=$(['<div style="text-align: left;">','<h2 style="margin-bottom: 15px;">Subscribe to the '+b+" weekly newsletter</h2>",'<p><strong><a href="/users/login?returnurl=/newsletter/signup/redirect">Create an account on '+b+'</a> or <a href="/users/login?returnurl=/newsletter/signup/redirect">log in</a> if you already have one.</strong></p>','<form><label for="newsletter-email-input">Or, send newsletter emails to:</label> <input type="text" id="newsletter-email-input" maxlength="100" title="your email address" /> <input type="submit" value="Subscribe" id="newsletter-email-submit" /></form></div>'].join(""));
a.find("form").submit(function(){var b=$(this),c=$.trim(a.find("#newsletter-email-input").val());if(0==c.length)return!1;StackExchange.helpers.addSpinner(b);$.ajax({url:"/newsletter/signup/anon",type:"POST",dataType:"json",data:{email:c},success:function(a){"confirmed"==a.status&&!a.error?(b.find("#newsletter-email-input").attr("disabled",!0),b.find("#newsletter-email-submit").replaceWith('<span style="line-height: 120%; text-align: center;"><strong>Subscribed!</strong></span>'),$("#newsletter-signup-container").replaceWith('<div style="line-height: 200%; text-align: center;"><strong>Subscribed!</strong></div>')):
"unconfirmed"==a.status&&!a.error?(b.find("#newsletter-email-input").attr("disabled",!0),b.find("#newsletter-email-submit").replaceWith('<span style="line-height: 120%; text-align: center;"><strong>Subscribed!</strong></span>'),b.append("<br /><br/><p><em>Please click the link in the confirmation email to activate your subscription.</em></p>"),$("#newsletter-signup-container").replaceWith('<span style="line-height: 120%;"><strong>Success!</strong> Please click the link in the confirmation email to activate your subscription.</span>')):
b.showErrorPopup(a.error||"there was a problem signing up for the newsletter<br />please try again later")},error:function(){b.showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},complete:function(){StackExchange.helpers.removeSpinner(b)}});return!1});d(a)}return{init:function(){$("#newsletter-signup").click(function(){var b=$(this);if(StackExchange.options.user.isAnonymous)return c(),!1;StackExchange.helpers.addSpinner("#newsletter-signup-container");
$.ajax({url:"/newsletter/signup",type:"POST",dataType:"json",success:function(a){a.url?window.location.href=a.url:"confirmed"==a.status?$("#newsletter-signup-container").replaceWith('<div style="line-height: 200%; text-align: center;"><strong>Subscribed!</strong></div>'):"unconfirmed"==a.status?$("#newsletter-signup-container").replaceWith('<span style="line-height: 120%;"><strong>Success!</strong> Please click the link in the confirmation email to activate your subscription.</span>'):b.parent().showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},
error:function(){b.parent().showErrorPopup("there was a problem signing up for the newsletter<br />please try again later")},complete:function(){StackExchange.helpers.removeSpinner("#newsletter-signup-container")}})});$("#newsletter-preview").click(function(){var b=$(window).height(),b=Math.min(600,b-100),b=['<div id="newsleter-preview-pane" style="overflow: hidden; width: 660px; height: ',b,'px;"><iframe src="',$(this).attr("href"),'" width="660" height="',b,'" frameborder="0"></iframe></div>'].join("");
d(b);return!1})},loader:function(b,a){var b=a||b,c=$(".newuser-greeting");$.ajax({url:"/newsletter/targetted/ajax",data:{domain:b},success:function(a){$("#newsletter-ad").remove();c.empty().append($(a))},complete:function(){c.attr("class","").attr("style","")}});a||(window.sessionStorage.tNewsletter=b+"-continued")}}}();
(function(d,c,b,a){d.fn.caret=function(g,e){var h,j,i=this[0],k=d.browser.msie;"object"===typeof g&&"number"===typeof g.start&&"number"===typeof g.end?(h=g.start,j=g.end):"number"===typeof g&&"number"===typeof e?(h=g,j=e):"string"===typeof g?-1<(h=i.value.indexOf(g))?j=h+g[c]:h=null:"[object RegExp]"===Object.prototype.toString.call(g)&&(g=g.exec(i.value),null!=g&&(h=g.index,j=h+g[0][c]));if("undefined"!=typeof h)return k?(k=this[0].createTextRange(),k.collapse(!0),k.moveStart("character",h),k.moveEnd("character",
j-h),k.select()):(this[0].selectionStart=h,this[0].selectionEnd=j),this[0].focus(),this;if(k)if(j=document.selection,"textarea"!=this[0].tagName.toLowerCase()){k=this.val();h=j[b]()[a]();h.moveEnd("character",k[c]);var f=""==h.text?k[c]:k.lastIndexOf(h.text);h=j[b]()[a]();h.moveStart("character",-k[c]);var l=h.text[c]}else h=j[b](),j=h[a](),j.moveToElementText(this[0]),j.setEndPoint("EndToEnd",h),f=j.text[c]-h.text[c],l=f+h.text[c];else f=i.selectionStart,l=i.selectionEnd;h=i.value.substring(f,l);
return{start:f,end:l,text:h,replace:function(a){return i.value.substring(0,f)+a+i.value.substring(l,i.value[c])}}}})(jQuery,"length","createRange","duplicate");
